### ISSUE TITLE
feat: ProxyFactory + Proxy

### ISSUE THREAD

**Issue by abigger87** [pentagonxyz/huffmate#24]
## Overview

We need a factory for creating proxies similar to openzeppelin's [Clones.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol). Will also require the introduction of a [Proxy.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Proxy.sol) contract.

**Comment by cheethas** [comment]
Closed by #61 LFG
