### ISSUE TITLE
issue: ERC20 decimals should be uint8

### ISSUE THREAD

**Issue by eugenioclrc** [pentagonxyz/huffmate#95]
According to [ERC20 especification](https://eips.ethereum.org/EIPS/eip-20#specification) the `decimals` shoud be defined as;
```
function decimals() public view returns (uint8)
```

But in [ERC20.huff#L29](https://github.com/pentagonxyz/huffmate/blob/main/src/tokens/ERC20.huff#L29) this is the definition;
```
#define function decimals() nonpayable returns (uint256)
```

Shouldnt be this definition?
```
#define function decimals() nonpayable returns (uint8)
```

**Comment by cheethas** [comment]
Good spot, we will get that fixed, thank you!

**Comment by eugenioclrc** [comment]
Submit this pull request with a proposed fix;
https://github.com/pentagonxyz/huffmate/pull/105

**Comment by cheethas** [comment]
Thank you!
